flows:
  - names: yuncms
    language: php
    version: 5.5.32

    env:
      - FLOW_PROJECT_PATH=./
      - DB=mysql

    trigger:
      push:
        - develop
        - master
      pull_request: true

    steps:
      - name: Init
        plugin:
          name: php_init

      - name: Git Clone
        plugin:
          name: git

      - name: MySQL
        plugin:
          name: mysql_database

      - name: Install
        failure: true
        plugin:
          name: php_install

      - name: Test
        scripts:
          - cd $FLOW_CURRENT_PROJECT_PATH
          - php think unit
